# -*- coding: utf-8 -*-
"""streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12M459BWVXzkmIPR7Ttlj5QA73IQLaO10
"""

import pickle
from pathlib import Path
import pandas as pd
import numpy as np
import os
import pickle
from pathlib import Path
import streamlit as st
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
from pandasai.callbacks import BaseCallback
from pandasai.responses.response_parser import ResponseParser
import warnings 


def load_file(path: str) -> str:
    with open(path, "rb") as f:
      dataset = pickle.load(f)
    return dataset

# Initialize the page
@st.cache_data
def load_data(folder: str)-> pd.DataFrame:
  all_dataset = [load_file(file) for file in Path(folder).interdir()]
  df = pd.concat (all_datasets)
  return df
